### PR TITLE
Show unsupported system property values nicely in the report

### PR DESCRIPTION
**Pull request by mlopatkin**
See https://github.com/gradle/gradle/pull/20245 for the accompanying change in the build tool

### CODE REVIEW

**Comment by bamboo** [comment]
Could you add a system property node sample to `src/test/resources/configuration-cache-report-data.js`?

**Comment by mlopatkin** [comment]
> Could you add a system property node sample to src/test/resources/configuration-cache-report-data.js?

Done. I suppose having `totalProblemCount` greater than the actual number of problems is intentional there?

**Comment by bamboo** [comment]
> I suppose having totalProblemCount greater than the actual number of problems is intentional there?

Yes, thanks.

**Review by bamboo — APPROVED** [review]
💯

**Pull request merged**
