### PR TITLE
v1.2: Add Project and PropertyUsage trace elements

### PR DESCRIPTION
**Pull request by h0tk3y**

### CODE REVIEW

**Review by abstratt — COMMENTED** [review]
Looks good! Can you share a screenshot of the resulting report? 

Only nitpick is the use of ['lookup' as a verb](https://english.stackexchange.com/a/555267), but that would be in Gradle itself, not in the report.

**Comment by h0tk3y** [comment]
> Looks good! Can you share a screenshot of the resulting report?

@abstratt Here's a screenshot:

image

**Review by abstratt — APPROVED** [review]
LGTM!

**Review by bamboo — COMMENTED** [review]
💯

**Pull request merged**
